blank_issues_enabled: false
contact_links:
  - name: "Join the Community Group"
    about: Join the Infinite World community to discuss ideas and get help from others
    url: https://discord.gg/bYdVPGqEsf
